# Generated by Django 2.2.1 on 2019-07-23 10:32

import accounts.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KycModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_address', models.FileField(blank=True, upload_to=accounts.models.user_directory_path)),
                ('curr_address', models.FileField(blank=True, upload_to=accounts.models.user_directory_path)),
                ('primary_contact', models.CharField(blank=True, max_length=10)),
                ('secondary_contact', models.CharField(blank=True, max_length=10)),
                ('delivery_address', models.CharField(choices=[('p', 'Permanent Address'), ('c', 'Current Address')], default='p', max_length=1)),
                ('kyc_verified', models.CharField(choices=[('y', 'Verified'), ('n', 'Not Verified')], default='n', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
