# Generated by Django 2.2.1 on 2019-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='buyorder',
            name='city_choice',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Jabalpur', 'Jabalpur'), ('Goa', 'Goa'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Gwalior', 'Gwalior'), ('Gurgaon', 'Gurgaon')], default='Jabalpur', max_length=15),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='payment_status',
            field=models.CharField(choices=[('p', 'PAID'), ('u', 'NOT PAID')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='city_choice',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Jabalpur', 'Jabalpur'), ('Goa', 'Goa'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Gwalior', 'Gwalior'), ('Gurgaon', 'Gurgaon')], default='Jabalpur', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'PAID'), ('u', 'NOT PAID')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='city_choice',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Jabalpur', 'Jabalpur'), ('Goa', 'Goa'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Gwalior', 'Gwalior'), ('Gurgaon', 'Gurgaon')], default='Jabalpur', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
